# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless-ngx
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: cloudnative-pg
      namespace: database
  values:
    controllers:
      main:
        initContainers:
          01-init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16.8
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: paperless-ngx-postgres-secret
        containers:
          app:
            image:
              repository: ghcr.io/paperless-ngx/paperless-ngx
              tag: 2.14.7
              pullPolicy: IfNotPresent
            env:
              COMPOSE_PROJECT_NAME: paperless-ngx
              PAPERLESS_TIME_ZONE: US/Central
              PAPERLESS_URL: https://docs.${SECRET_DOMAIN}
              PAPERLESS_FILENAME_FORMAT: "{created_year}/{correspondent}/{title}"
              PAPERLESS_FILENAME_FORMAT_REMOVE_NONE: true
              PAPERLESS_CONSUMER_POLLING: 60
              PAPERLESS_CONSUMER_DELETE_DUPLICATES: true
              PAPERLESS_CONSUMER_RECURSIVE: true
              PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: true
              PAPERLESS_OCR_USER_ARGS: >
                {
                  "invalidate_digital_signatures": true,
                  "continue_on_soft_render_error": true
                }
              PAPERLESS_OCR_LANGUAGE: eng
              PAPERLESS_TIKA_ENABLED: true
            envFrom:
              - secretRef:
                  name: paperless-ngx-secret
          tika:
            image:
              repository: ghcr.io/paperless-ngx/tika
              tag: 2.9.1-minimal
              pullPolicy: IfNotPresent
            ports:
              - containerPort: 9998
          gotenberg:
            image:
              repository: gotenberg/gotenberg
              tag: 8.17.3
              pullPolicy: IfNotPresent
            ports:
              - containerPort: 3000
            command:
              - "gotenberg"
              - "--chromium-disable-javascript=true"
              - "--chromium-allow-list=file:///tmp/.*"
    service:
      app:
        controller: main
        ports:
          http:
            port: 8000
    ingress:
      app:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN}"
          authentik.home.arpa/internal: "true"
          nginx.ingress.kubernetes.io/auth-signin: "https://docs.${SECRET_DOMAIN}/outpost.goauthentik.io/start?rd=$scheme://$http_host$escaped_request_uri"
        className: internal
        hosts:
          - host: &host docs.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
            secretName: ${SECRET_DOMAIN/./-}-tls
    persistence:
      data:
        existingClaim: paperless-ngx
        advancedMounts:
          main:
            app:
              - path: /data/local
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 150
        fsGroup: 140
        fsGroupChangePolicy: "OnRootMismatch"
