---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rtlamr2mqtt
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: rtlamr2mqtt-secret
    template:
      engineVersion: v2
      data:
        rtlamr2mqtt.yaml: |
          general:
            sleep_for: 0
            verbosity: debug
            tickle_rtl_tcp: false
            device_id: 0bda:2838
          mqtt:
            host: emqx-listeners.database.svc.cluster.local
            port: 1883
            tls_enabled: false
            user: "{{ .EMQX_MQTT_HOME_USERNAME }}"
            password: "{{ .EMQX_MQTT_HOME_PASSWORD }}"
            ha_autodiscovery: true
            ha_autodiscovery_topic: homeassistant
            base_topic: rtlamr
          custom_parameters:
            rtltcp: -s 2048000
            rtlamr: -unique=true -symbollength=32
          meters:
            - id: "{{ .RTLAMR2MQTT_METER_ID }}"
              protocol: scm
              name: home_energy_meter
              format: "######"
              unit_of_measurement: kWh
              icon: mdi:gauge
              device_class: energy
  dataFrom:
    - find:
        path: EMQX_MQTT_HOME_USERNAME
    - find:
        path: EMQX_MQTT_HOME_PASSWORD
    - find:
        path: RTLAMR2MQTT_METER_ID
