---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns-bind
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: extnernal-dns-bind-secret
    template:
      engineVersion: v2
      data:
        BIND_ZONE_NAME:  '{{ .BIND_ZONE_NAME }}'
        BIND_RNDC_ALG: '{{ .BIND_RNDC_ALG }}'
        BIND_RNDC_KEY:  '{{ .BIND_RNDC_KEY }}'
  dataFrom:
    - find:
        name:
          regexp: ^BIND.*
