---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Helm Repository Sync"

on:
  workflow_dispatch:
    inputs:
      helmRepoNamespace:
        description: Helm Repository Namespace
        default: flux-system
        required: true
      helmRepoName:
        description: Helm Repository Name
        required: true
  pull_request:
    branches: ["main"]
    paths: ["kubernetes/**/helmrelease.yaml"]

env:
  HOMEBREW_NO_ANALYTICS: "1"

jobs:
  sync:
    name: Helm Repository Sync
    runs-on: ["dapper-cluster-runner"]
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Generate Token
        uses: actions/create-github-app-token@21cfef2b496dd8ef5b904c159339626a10ad380e # v1.11.6
        id: app-token
        with:
          app-id: "${{ secrets.DUNCE_BOT_APP_ID }}"
          private-key: "${{ secrets.DUNCE_BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@4e53f9c809b54e432fc49f7ee18e56ee4aa45bdc # master

      - name: Setup Workflow Tools
        run: brew install fluxcd/tap/flux

      - if: ${{ github.event.inputs.helmRepoNamespace == '' && github.event.inputs.helmRepoName == '' }}
        name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@48d8f15b2aaa3d255ca5af3eba4870f807ce6b3c # v45.0.2
        with:
          files: kubernetes/**/helmrelease.yaml
          safe_output: false

      - if: ${{ github.event.inputs.helmRepoNamespace == '' && github.event.inputs.helmRepoName == '' }}
        name: Sync Helm Repository
        run: |
          declare -A repos=()
          for f in ${{ steps.changed-files.outputs.all_changed_and_modified_files }}; do
              repo_namespace="$(yq -r '.spec.chart.spec.sourceRef.namespace' "${f}")"
              repo_name="$(yq -r '.spec.chart.spec.sourceRef.name' "${f}")"
              repos["${repo_namespace}:${repo_name}"]=1
          done
          for r in "${!repos[@]}"; do
              IFS=':' read -r repo_namespace repo_name <<< "${r}"
              flux --namespace ${repo_namespace} \
                  reconcile source helm ${repo_name} || true
          done

      - if: ${{ github.event.inputs.helmRepoNamespace != '' && github.event.inputs.helmRepoName != '' }}
        name: Sync Helm Repository
        run: |
          flux --namespace ${{ github.event.inputs.helmRepoNamespace }} \
              reconcile source helm ${{ github.event.inputs.helmRepoName }} || true
