---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Renovate"

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: Dry Run
        default: "false"
        required: false
      logLevel:
        description: Log Level
        default: debug
        required: false
      version:
        description: Renovate version
        default: latest
        required: false
  schedule:
    - cron: "0 * * * *" # Every hour
  push:
    branches: ["main"]
    paths:
      - .github/renovate.json5
      - .github/renovate/**.json5

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  LOG_LEVEL: "${{ inputs.logLevel || 'debug' }}"
  RENOVATE_AUTODISCOVER: true
  RENOVATE_AUTODISCOVER_FILTER: "${{ github.repository }}"
  RENOVATE_DRY_RUN: "${{ inputs.dryRun == true }}"
  RENOVATE_PLATFORM: github
  RENOVATE_PLATFORM_COMMIT: true
  WORKFLOW_RENOVATE_VERSION: "${{ inputs.version || 'latest' }}"

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Generate Token
        uses: actions/create-github-app-token@21cfef2b496dd8ef5b904c159339626a10ad380e # v1.11.6
        id: app-token
        with:
          app-id: "${{ secrets.DUNCE_BOT_APP_ID }}"
          private-key: "${{ secrets.DUNCE_BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Renovate
        uses: renovatebot/github-action@02f4fdeb479bbb229caa7ad82cb5e691c07e80b3 # v41.0.14
        with:
          configurationFile: .github/renovate.json5
          token: "${{ steps.app-token.outputs.token }}"
          renovate-version: "${{ env.WORKFLOW_RENOVATE_VERSION }}"
