---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app open-webui
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: open-webui
      version: 5.24.0
      sourceRef:
        kind: HelmRepository
        name: *app
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: ollama
      namespace: ai
    - name: volsync
      namespace: storage

  values:
    annotations:
      reloader.stakater.com/auto: "true"
    copyAppData:
      resources: {}
    ollama:
      enabled: false
    ollamaUrls: ["http://ollama.ai.svc.cluster.local:11434"]
    pipelines:
      enabled: true
      persistence:
        existingClaim: open-webui-pipelines
    tika:
      enabled: true
    websocket:
      enabled: true

    extraEnvVars:
      - name: ENABLE_LOGIN_FORM
        value: "false"
      - name: OAUTH_PROVIDER_NAME
        value: authentik
      - name: ENABLE_OAUTH_SIGNUP
        value: "true"
      - name: OPENID_PROVIDER_URL
        valueFrom:
          secretKeyRef:
            name: *app
            key: OPENID_PROVIDER_URL
      - name: OAUTH_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: *app
            key: OAUTH_CLIENT_ID
      - name: OAUTH_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: *app
            key: OAUTH_CLIENT_SECRET
      - name: WEBUI_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: *app
            key: WEBUI_SECRET_KEY
      - name: OPENAI_API_KEY
        valueFrom:
          secretKeyRef:
            name: *app
            key: OPENAI_API_KEY
    ingress:
      enabled: true
      class: internal
      annotations:
        external-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN}"
        nginx.ingress.kubernetes.io/server-snippet: |
          # Add WebSocket support
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";

          # Timeouts for WebSocket connections
          proxy_read_timeout 60s;
          proxy_send_timeout 60s;

      host: chat.${SECRET_DOMAIN}
      tls: true
      existingSecret: ${SECRET_DOMAIN/./-}-tls
    persistence:
      enabled: true
      existingClaim: open-webui
    podSecurityContext:
      supplementalGroups: [140]
    containerSecurityContext:
      runAsUser: 1000
      runAsGroup: 150
      runAsNonRoot: true
      privileged: false
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: false
      capabilities: { drop: ["ALL"] }
      seccompProfile: { type: RuntimeDefault }
